### ISSUE TITLE
ICMP Linux Permission Denied

### ISSUE THREAD

**Issue by compscidr** [compscidr/icmp#151]
On a github runner, I'm getting the following error:
```
Exception in thread "DefaultDispatcher-worker-1 @coroutine#1" java.io.IOException: open: Permission denied
	at com.jasonernst.icmp_linux.ICMPLinux.socket(Native Method)
	at com.jasonernst.icmp_linux.ICMPLinux.obtainSocketIpv6Socket(ICMPLinux.kt:59)
	at com.jasonernst.icmp_common.ICMP$openAndPrepareSocket$2.invokeSuspend(ICMP.kt:88)
	at com.jasonernst.icmp_common.ICMP$openAndPrepareSocket$2.invoke(ICMP.kt)
	at com.jasonernst.icmp_common.ICMP$openAndPrepareSocket$2.invoke(ICMP.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jasonernst.icmp_common.ICMP.openAndPrepareSocket(ICMP.kt:82)
	at com.jasonernst.icmp_common.ICMP.ping-oSehluM(ICMP.kt:74)
	at com.jasonernst.icmp_common.ICMP.ping-oSehluM$default(ICMP.kt:73)
	at com.jasonernst.kanonproxy.KAnonProxy.handleICMPPacket(KAnonProxy.kt:85)
	at com.jasonernst.kanonproxy.KAnonProxy$handlePackets$1$1.invokeSuspend(KAnonProxy.kt:60)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.jasonernst.icmp_common.ICMP.ping-oSehluM(ICMP.kt:74)
	at com.jasonernst.kanonproxy.KAnonProxy.handleICMPPacket(KAnonProxy.kt:85)
	at com.jasonernst.kanonproxy.KAnonProxy$handlePackets$1$1.invokeSuspend(KAnonProxy.kt:60)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(1), "coroutine#1":StandaloneCoroutine{Cancelling}@60520ed0, Dispatchers.IO]
```

IIRC, I had to toggle on some kernel setting to allow for userspace pings. Probably should document that better

**Comment by compscidr** [comment]
https://opennms.discourse.group/t/how-to-allow-unprivileged-users-to-use-icmp-ping/1573

**Comment by compscidr** [comment]
Also, the same parameter controls ipv6 ping permission too: https://github.com/iputils/iputils/issues/105#issuecomment-431475908
